"""empty message

Revision ID: 36f32acd977f
Revises: d4ab7d0e7a8e
Create Date: 2018-10-25 09:01:01.398699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36f32acd977f'
down_revision = 'd4ab7d0e7a8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('translations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('original', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('translation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'translations_pkey')
    )
    # ### end Alembic commands ###
