"""empty message

Revision ID: e22a152ccbf2
Revises: 36f32acd977f
Create Date: 2018-10-25 15:05:49.112807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e22a152ccbf2'
down_revision = '36f32acd977f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_text', sa.String(length=512), nullable=True),
    sa.Column('translation_text', sa.String(length=512), nullable=True),
    sa.Column('uid', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('translations')
    # ### end Alembic commands ###
