"""empty message

Revision ID: f0220ff558f7
Revises: e22a152ccbf2
Create Date: 2018-10-25 16:36:37.173751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0220ff558f7'
down_revision = 'e22a152ccbf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('translations', sa.Column('source_text', sa.String(length=512), nullable=True))
    op.add_column('translations', sa.Column('translated_text', sa.String(length=512), nullable=True))
    op.drop_column('translations', 'original_text')
    op.drop_column('translations', 'translation_text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('translations', sa.Column('translation_text', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.add_column('translations', sa.Column('original_text', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.drop_column('translations', 'translated_text')
    op.drop_column('translations', 'source_text')
    # ### end Alembic commands ###
